### ISSUE TITLE
implementation of google oauth

### ISSUE THREAD

**Issue by AbubakrChan** [nikhilno1/interview-gpt#4]
Hi there!

I noticed that once I reload the streamlit app I immediately get signed out, this is the problem that I also faced when I implemented google auth in my streamlit app and luckily I was able to solve it using cookies.

Here is the post of mine showing demo of the app I made back in jul 2023 showing how I preserved the user session via cookies:
https://discuss.streamlit.io/t/i-implemented-google-oauth-used-cookies-to-save-session/46941/4

Pleae let me know if you are interested for a similar solution.

Looking forward to discuss further with you @nikhilno1 

Best
Chan

**Comment by nikhilno1** [comment]
This functionality is now added by @AbubakrChan . Thank You.
